"""empty message

Revision ID: 768886a33a2c
Revises: 8ed57d7bc5b0
Create Date: 2020-03-18 16:16:27.097989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '768886a33a2c'
down_revision = '8ed57d7bc5b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('website', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'website')
    # ### end Alembic commands ###
