"""empty message

Revision ID: 8ed57d7bc5b0
Revises: ab32c1d19e7d
Create Date: 2020-03-08 19:02:28.376920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ed57d7bc5b0'
down_revision = 'ab32c1d19e7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    op.add_column('artist', sa.Column('seeking_venue', sa.BOOLEAN(), server_default=sa.text('false'), nullable=True))
    op.drop_column('artist', 'seek_venue')
    op.drop_column('artist', 'seek_description')
    op.add_column('venue', sa.Column('seeking_description', sa.String(length=120), nullable=True))
    op.add_column('venue', sa.Column('seeking_talent', sa.BOOLEAN(), server_default=sa.text('false'), nullable=True))
    op.drop_column('venue', 'seek_description')
    op.drop_column('venue', 'seek_talent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('seek_talent', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('venue', sa.Column('seek_description', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('venue', 'seeking_talent')
    op.drop_column('venue', 'seeking_description')
    op.add_column('artist', sa.Column('seek_description', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('artist', sa.Column('seek_venue', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_column('artist', 'seeking_venue')
    op.drop_column('artist', 'seeking_description')
    # ### end Alembic commands ###
